openapi: 3.0.0
info:
  title: ITRIS Chat API
  version: 1.0.0
  description: >
    API WebSocket para interacción con un chatbot experto en manuales ITRIS.  
    La comunicación se realiza mediante eventos WebSocket.

servers:
  - url: ws://localhost:3000
    description: Servidor de desarrollo local
  - url: wss://chat.itris.com.ar
    description: Servidor de producción

paths:
  /socket.io:
    post:
      summary: Establece una conexión WebSocket con el servidor ITRIS Chat.
      description: >
        Al conectarse, el cliente obtiene un ID de sesión.  
        Puede enviar mensajes a través del evento `mensaje_cliente` y recibirá respuestas en `mensaje_servidor`.
      responses:
        '101':
          description: Protocolo de cambio exitoso a WebSocket

components:
  schemas:
    MensajeCliente:
      type: object
      properties:
        texto:
          type: string
          example: "¿Cómo se autorizan bonificaciones por artículo?"
      required:
        - texto

    MensajeServidor:
      type: object
      properties:
        respuesta:
          type: string
          example: "Para autorizar bonificaciones por artículo debes..."
    
    ChatMessage:
      type: object
      properties:
        role:
          type: string
          enum: [user, assistant]
        content:
          type: string

tags:
  - name: WebSocket
    description: Comunicación mediante eventos WebSocket

